run:
    tests: false
    timeout: 5m
linters:
    disable-all: true
    enable:
        - deadcode
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - structcheck
        - typecheck
        - unused
        - varcheck
        - dupl
        - funlen
        - goconst
        - gocyclo
        - gocritic
        - goimports
        - goprintffuncname
        - gosec
        - lll
        - misspell
        - nakedret
        - prealloc
        - unconvert
        - unparam
        - bodyclose
linters-settings:
    funlen:
        lines: 150
        statements: 80
    govet:
        disable:
            - composites
